name:                gadts
version:             0.1.0.0

extra-source-files:
- README.md

description:         gadts

ghc-options:
- -Wall
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wno-unused-top-binds
- -Wno-unused-local-binds
- -Wno-unused-pattern-binds
- -Wno-unused-matches
- -Wno-missing-signatures
- -Wno-type-defaults
- -Wno-compat-unqualified-imports
- -Wno-name-shadowing

language: GHC2021

default-extensions:
- GADTs
- DataKinds

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  gadts-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gadts
    when:
    - condition: false
      other-modules: Paths_gadts
